version: 2.1

jobs:
  test-java:  # Job pour exécuter les tests et générer la couverture de code
    docker:
      - image: cimg/openjdk:11.0  # Utilisez cimg/openjdk:8.0 si Java 8 est nécessaire
    steps:
      - checkout  # Récupère le code source
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}  # Restaure le cache en utilisant le checksum
      - run:
          name: Run Maven Tests with Coverage
          command: mvn verify  # Exécute les tests Maven avec JaCoCo
      - store_test_results:
          path: target/surefire-reports  # Sauvegarde les résultats des tests
      - store_artifacts:
          path: target/site/jacoco  # Sauvegarde le rapport de couverture généré par JaCoCo
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}  # Sauvegarde le cache pour les dépendances Maven
          paths:
            - ~/.m2/repository  # Cache les dépendances Maven pour une exécution plus rapide

      # Publier les rapports de couverture sur Codecov
      - run:
          name: Upload to Codecov
          command: |
            curl -s https://codecov.io/bash > /tmp/codecov  # Télécharge le script de Codecov
            bash /tmp/codecov  # Exécute le script pour uploader les résultats de couverture

  checkstyle:  # Nouveau job pour exécuter CheckStyle
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run CheckStyle
          command: mvn checkstyle:checkstyle  # Exécute le plugin CheckStyle
      - store_artifacts:
          path: target/site/checkstyle.html  # Sauvegarde le rapport CheckStyle HTML
      - store_artifacts:
          path: target/checkstyle-result.xml  # Sauvegarde le rapport CheckStyle XML
      - run:
          name: Push CheckStyle result to GitHub
          command: |
            # Crée le dossier checkstyle-reports si il n'existe pas déjà
            mkdir -p checkstyle-reports
            # Déplace le fichier checkstyle-result.xml dans ce dossier
            mv target/checkstyle-result.xml checkstyle-reports/checkstyle-result.xml || true
            # Configurer Git pour permettre le push
            git config --global user.email "circleci-bot@example.com"
            git config --global user.name "CircleCI Bot"
            # Ajouter les fichiers directement en forçant l'ajout malgré .gitignore
            git add -f checkstyle-reports/checkstyle-result.xml
            git commit -m "Add CheckStyle result [skip ci]" || echo "No changes to commit"
            # Pousser vers le dépôt GitHub
            git push origin $(git rev-parse --abbrev-ref HEAD)

workflows:
  build-and-upload:  # Workflow pour construire, tester et uploader les résultats
    jobs:
      - test-java:  # Le job test-java s'exécute
          filters:
            branches:
              only:
                - master  # Exécute le job uniquement sur la branche master
      - checkstyle:  # Exécute le job CheckStyle
          filters:
            branches:
              only:
                - master
